apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/data"
    server: 10.10.1.0/24